"use client";

import { useCallback, useEffect, useState } from "react";
import { useToasts } from "@/components/ToastProvider";
import { friendlyError } from "@/lib/clientErrors";
import type { DailyReport, ReportAction, ReportTicket } from "@/lib/types";

const PYLON_BASE_URL = process.env.NEXT_PUBLIC_PYLON_APP_URL ?? "https://app.usepylon.com";

const ACTION_LABELS: Record<ReportAction, string> = {
  close: "Close now",
  follow_up: "Follow up",
  confirmation: "Send confirmation",
  analyze: "Awaiting analysis",
};

const ACTION_BADGES: Record<ReportAction, string> = {
  close: "border-emerald-200 bg-emerald-50 text-emerald-700",
  follow_up: "border-amber-200 bg-amber-50 text-amber-700",
  confirmation: "border-violet-200 bg-violet-50 text-violet-700",
  analyze: "border-zinc-200 bg-zinc-50 text-zinc-500",
};

const STALE_BADGE = "border-rose-200 bg-rose-100 text-rose-700";

function Spinner() {
  return (
    <span className="inline-block h-3.5 w-3.5 shrink-0 animate-spin rounded-full border-2 border-zinc-200 border-t-indigo-500" />
  );
}

function ticketUrl(t: ReportTicket): string {
  return t.url ?? `${PYLON_BASE_URL}/issues/${t.number}`;
}

function waitLabel(t: ReportTicket): string {
  if (t.days_since_support_reply !== null) return `${t.days_since_support_reply}d since last reply`;
  if (t.idle_days !== null) return `idle ${t.idle_days}d`;
  return "";
}

function formatReportDate(iso: string): { date: string; time: string } {
  const d = new Date(iso);
  return {
    date: d.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" }),
    time: d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }),
  };
}

/** Plain-text rendering of the report, ready to paste into email or Slack. */
function reportToText(report: DailyReport): string {
  const { date, time } = formatReportDate(report.generated_at);
  const lines: string[] = [];
  const c = report.counts;

  lines.push(`DAILY TICKET REPORT — ${date} · ${time}`);
  lines.push("=".repeat(60));
  lines.push(`${report.total} open non-admin tickets`);
  lines.push(`  • ${c.close} ready to close now`);
  lines.push(
    `  • ${c.follow_up} need follow-up${report.stale_count > 0 ? ` (${report.stale_count} overdue — no reply in 3+ days)` : ""}`,
  );
  lines.push(`  • ${c.confirmation} ready for confirmation`);
  if (c.analyze > 0) lines.push(`  • ${c.analyze} awaiting analysis`);
  if (report.snoozed_count > 0) lines.push(`  • ${report.snoozed_count} snoozed (excluded below)`);

  const allTickets = report.assignees.flatMap((a) => a.tickets.map((t) => ({ ...t, assignee: a.assignee })));

  const closable = allTickets.filter((t) => t.action === "close");
  if (closable.length > 0) {
    lines.push("");
    lines.push(`READY TO CLOSE NOW (${closable.length})`);
    for (const t of closable) {
      lines.push(`  #${t.number} · ${t.assignee} · ${waitLabel(t)} — ${t.title}`);
    }
  }

  const overdue = allTickets.filter((t) => t.stale);
  if (overdue.length > 0) {
    lines.push("");
    lines.push(`OVERDUE FOLLOW-UPS — NO SUPPORT REPLY IN 3+ DAYS (${overdue.length})`);
    for (const t of overdue) {
      lines.push(`  #${t.number} · ${t.assignee} · ${waitLabel(t)} — ${t.title}`);
    }
  }

  lines.push("");
  lines.push("BY ASSIGNEE");
  lines.push("-".repeat(60));
  for (const a of report.assignees) {
    const parts: string[] = [];
    if (a.stale_count > 0) parts.push(`${a.stale_count} overdue`);
    if (a.counts.follow_up > 0) parts.push(`${a.counts.follow_up} follow-up`);
    if (a.counts.confirmation > 0) parts.push(`${a.counts.confirmation} confirmation`);
    if (a.counts.close > 0) parts.push(`${a.counts.close} close`);
    if (a.counts.analyze > 0) parts.push(`${a.counts.analyze} unanalyzed`);
    lines.push("");
    lines.push(`${a.assignee} — ${a.tickets.length} open${parts.length ? ` (${parts.join(", ")})` : ""}`);
    for (const t of a.tickets) {
      const marker = t.stale ? "!" : "•";
      const action = t.stale ? "OVERDUE follow-up" : ACTION_LABELS[t.action];
      const wait = waitLabel(t);
      const draft = t.action === "confirmation" && t.has_draft ? ", draft ready" : "";
      lines.push(`  ${marker} #${t.number} — ${action}${wait ? ` (${wait}${draft})` : ""} — ${t.title}`);
      lines.push(`      ${ticketUrl(t)}`);
    }
  }

  lines.push("");
  lines.push("Generated by the Hadrius ticket triage dashboard.");
  return lines.join("\n");
}

function SummaryCard({ value, label, sub, tint, accent }: {
  value: number;
  label: string;
  sub?: string;
  tint: string;
  accent: string;
}) {
  return (
    <div className={`flex-1 rounded-xl border px-5 py-4 ${tint}`}>
      <div className={`text-sm font-medium ${accent}`}>{label}</div>
      <div className="mt-1.5 text-3xl font-semibold text-zinc-900">{value}</div>
      {sub && <div className="mt-1 text-xs text-zinc-500">{sub}</div>}
    </div>
  );
}

function ActionBadge({ ticket }: { ticket: ReportTicket }) {
  const cls = ticket.stale ? STALE_BADGE : ACTION_BADGES[ticket.action];
  const label = ticket.stale ? "Overdue follow-up" : ACTION_LABELS[ticket.action];
  return (
    <span className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-medium whitespace-nowrap ${cls}`}>
      {label}
    </span>
  );
}

export default function ReportPage() {
  const { addToast } = useToasts();
  const [report, setReport] = useState<DailyReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // No synchronous setState before the first await — the mount effect below relies on that
  // (loading already starts true); the Refresh button flips the flags itself first.
  const load = useCallback(async () => {
    try {
      const res = await fetch("/api/report");
      const data = await res.json();
      if (!res.ok || !data.report) throw new Error(data.error ?? "Failed to build the report");
      setReport(data.report);
      setError(null);
    } catch (err) {
      setError(friendlyError(err, "Failed to build the report"));
    } finally {
      setLoading(false);
    }
  }, []);

  const refresh = useCallback(() => {
    setLoading(true);
    setError(null);
    void load();
  }, [load]);

  useEffect(() => {
    void (async () => {
      await load();
    })();
  }, [load]);

  const handleCopy = useCallback(async () => {
    if (!report) return;
    try {
      await navigator.clipboard.writeText(reportToText(report));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      addToast("Report copied — ready to paste into email or Slack", "success");
    } catch (err) {
      addToast(friendlyError(err, "Failed to copy the report"), "error");
    }
  }, [report, addToast]);

  const header = report ? formatReportDate(report.generated_at) : null;

  return (
    <div className="min-h-screen bg-white px-8 py-8 text-zinc-900">
      <div className="mx-auto max-w-6xl space-y-6">
        <header className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-semibold text-zinc-900">Daily Report</h1>
            <p className="mt-1 text-sm text-zinc-500">
              {header
                ? `${header.date} · generated ${header.time}`
                : "Open tickets by assignee, flagged with the action each one needs"}
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <button
              onClick={refresh}
              disabled={loading}
              className="inline-flex items-center gap-2 rounded-lg border border-zinc-200 bg-white px-3.5 py-1.5 text-sm font-medium text-zinc-700 hover:bg-zinc-50 disabled:opacity-50"
            >
              {loading && <Spinner />}
              Refresh
            </button>
            <button
              onClick={() => void handleCopy()}
              disabled={!report}
              title="Copies a plain-text version formatted for email or Slack"
              className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-3.5 py-1.5 text-sm font-medium text-white hover:bg-indigo-500 disabled:opacity-50"
            >
              {copied ? "Copied!" : "Copy for email / Slack"}
            </button>
          </div>
        </header>

        {error && (
          <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>
        )}

        {loading && !report ? (
          <div className="flex items-center justify-center gap-2 py-24 text-sm text-zinc-400">
            <Spinner />
            Building the report…
          </div>
        ) : report ? (
          <>
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-5">
              <SummaryCard
                value={report.total}
                label="Open tickets"
                sub={report.snoozed_count > 0 ? `+${report.snoozed_count} snoozed (excluded)` : undefined}
                tint="border-indigo-200 bg-indigo-50"
                accent="text-indigo-700"
              />
              <SummaryCard value={report.counts.close} label="Ready to close" tint="border-emerald-200 bg-emerald-50" accent="text-emerald-700" />
              <SummaryCard
                value={report.counts.follow_up}
                label="Need follow-up"
                sub={report.stale_count > 0 ? `${report.stale_count} overdue (3+ days)` : undefined}
                tint="border-amber-200 bg-amber-50"
                accent="text-amber-700"
              />
              <SummaryCard value={report.counts.confirmation} label="Send confirmation" tint="border-violet-200 bg-violet-50" accent="text-violet-700" />
              <SummaryCard
                value={report.counts.analyze}
                label="Awaiting analysis"
                tint="border-zinc-200 bg-zinc-50"
                accent="text-zinc-500"
              />
            </div>

            {report.stale_count > 0 && (
              <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
                <span className="font-semibold">{report.stale_count} overdue follow-up{report.stale_count === 1 ? "" : "s"}</span>{" "}
                — customers waiting 3+ days for a reply. These are listed first under each assignee below.
              </div>
            )}

            {report.assignees.length === 0 ? (
              <div className="rounded-xl border border-zinc-200 bg-zinc-50 px-4 py-16 text-center text-sm text-zinc-500">
                No open non-admin tickets — nothing to report. Sync the queue from the dashboard first if that
                seems wrong.
              </div>
            ) : (
              report.assignees.map((a) => (
                <section key={a.assignee} className="overflow-hidden rounded-xl border border-zinc-200 bg-white">
                  <div className="flex flex-wrap items-center justify-between gap-2 border-b border-zinc-200 bg-zinc-50 px-4 py-3">
                    <h2 className="text-sm font-semibold text-zinc-900">
                      {a.assignee}
                      <span className="ml-2 font-normal text-zinc-400">
                        {a.tickets.length} open ticket{a.tickets.length === 1 ? "" : "s"}
                      </span>
                    </h2>
                    <div className="flex flex-wrap items-center gap-1.5 text-xs">
                      {a.stale_count > 0 && (
                        <span className={`rounded-full border px-2 py-0.5 font-medium ${STALE_BADGE}`}>
                          {a.stale_count} overdue
                        </span>
                      )}
                      {a.counts.follow_up > 0 && (
                        <span className={`rounded-full border px-2 py-0.5 font-medium ${ACTION_BADGES.follow_up}`}>
                          {a.counts.follow_up} follow-up
                        </span>
                      )}
                      {a.counts.confirmation > 0 && (
                        <span className={`rounded-full border px-2 py-0.5 font-medium ${ACTION_BADGES.confirmation}`}>
                          {a.counts.confirmation} confirmation
                        </span>
                      )}
                      {a.counts.close > 0 && (
                        <span className={`rounded-full border px-2 py-0.5 font-medium ${ACTION_BADGES.close}`}>
                          {a.counts.close} close
                        </span>
                      )}
                      {a.counts.analyze > 0 && (
                        <span className={`rounded-full border px-2 py-0.5 font-medium ${ACTION_BADGES.analyze}`}>
                          {a.counts.analyze} unanalyzed
                        </span>
                      )}
                    </div>
                  </div>
                  <table className="w-full text-left">
                    <thead>
                      <tr className="border-b border-zinc-100 text-xs font-medium text-zinc-400">
                        <th className="py-2 pr-4 pl-4">Action</th>
                        <th className="py-2 pr-4">Ticket</th>
                        <th className="py-2 pr-4">Title</th>
                        <th className="py-2 pr-4">State</th>
                        <th className="py-2 pr-4">Waiting</th>
                        <th className="py-2 pr-4">Notes</th>
                      </tr>
                    </thead>
                    <tbody>
                      {a.tickets.map((t) => (
                        <tr key={t.number} className="border-b border-zinc-100 text-sm last:border-b-0 hover:bg-zinc-50">
                          <td className="py-2.5 pr-4 pl-4">
                            <ActionBadge ticket={t} />
                          </td>
                          <td className="py-2.5 pr-4">
                            <a
                              href={ticketUrl(t)}
                              target="_blank"
                              rel="noreferrer"
                              className="font-medium text-indigo-600 hover:underline"
                            >
                              #{t.number}
                            </a>
                          </td>
                          <td className="max-w-sm py-2.5 pr-4">
                            <div className="truncate text-zinc-700" title={t.title}>
                              {t.title}
                            </div>
                            {t.requester_name && <div className="text-xs text-zinc-400">{t.requester_name}</div>}
                          </td>
                          <td className="py-2.5 pr-4 text-zinc-500">{t.state.replace(/_/g, " ")}</td>
                          <td className={`py-2.5 pr-4 ${t.stale ? "font-medium text-rose-600" : "text-zinc-500"}`}>
                            {waitLabel(t) || "—"}
                          </td>
                          <td className="py-2.5 pr-4 text-xs text-zinc-500">
                            {t.action === "confirmation" && t.has_draft
                              ? "Draft reply ready — copy from the queue"
                              : t.action === "close" && t.has_draft
                                ? "Draft reply ready"
                                : ""}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </section>
              ))
            )}
          </>
        ) : null}
      </div>
    </div>
  );
}
